from PyQt5 import QtCore, QtGui, QtWidgets
import datetime

symbolRequireExpList = [12, 15, 20, 27, 36, 47, 60, 75, 92, 111, 132, 155, 180, 207, 236, 267, 300, 335, 372]
forceRequireExpList = [29, 76, 141, 224, 325, 444, 581, 736, 90, 1100]
requireMesoList_VJ = [9500000, 16630000, 23760000, 30890000, 38020000, 45150000, 52280000, 59410000, 66540000, 73670000, 80800000, 87930000, 95060000, 102190000, 109320000, 116450000, 123580000, 130710000, 137840000]
requireMesoList = [19040000, 25640000, 32240000, 38850000, 45440000, 52040000, 58640000, 65240000, 71840000, 78440000, 85040000, 91640000, 98240000, 104840000, 111440000, 124640000, 131240000, 137840000]
requireMesoListForce = [185400000, 273900000, 362400000, 450900000, 539400000, 62790000, 716400000, 804900000, 893400000, 981900000]
today = datetime.date.today()

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("ArcaneSymbolCalculator")
        Dialog.resize(1357, 820)
        self.vanishingJourney = QtWidgets.QGroupBox(Dialog)
        self.vanishingJourney.setGeometry(QtCore.QRect(40, 70, 301, 331))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.vanishingJourney.setFont(font)
        self.vanishingJourney.setObjectName("vanishingJourney")
        self.formLayoutWidget = QtWidgets.QWidget(self.vanishingJourney)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 30, 161, 57))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.formLayoutWidget.setFont(font)
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.currentLevelLabel_VJ = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.currentLevelLabel_VJ.setFont(font)
        self.currentLevelLabel_VJ.setObjectName("currentLevelLabel_VJ")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.currentLevelLabel_VJ)
        self.currentExpLabel_VJ = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.currentExpLabel_VJ.setFont(font)
        self.currentExpLabel_VJ.setObjectName("currentExpLabel_VJ")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.currentExpLabel_VJ)
        self.currentLevel_VJ = QtWidgets.QSpinBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.currentLevel_VJ.setFont(font)
        self.currentLevel_VJ.setObjectName("currentLevel_VJ")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.currentLevel_VJ)
        self.currentExp_VJ = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.currentExp_VJ.setFont(font)
        self.currentExp_VJ.setObjectName("currentExp_VJ")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.currentExp_VJ)
        self.expRatio_VJ = QtWidgets.QLabel(self.vanishingJourney)
        self.expRatio_VJ.setGeometry(QtCore.QRect(20, 90, 261, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.expRatio_VJ.setFont(font)
        self.expRatio_VJ.setAlignment(QtCore.Qt.AlignCenter)
        self.expRatio_VJ.setObjectName("expRatio_VJ")
        self.result_VJ = QtWidgets.QGroupBox(self.vanishingJourney)
        self.result_VJ.setGeometry(QtCore.QRect(10, 210, 281, 111))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.result_VJ.setFont(font)
        self.result_VJ.setObjectName("result_VJ")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.result_VJ)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 261, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.formLayoutWidget_2.setFont(font)
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.requireMesoLabel_VJ = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.requireMesoLabel_VJ.setFont(font)
        self.requireMesoLabel_VJ.setObjectName("requireMesoLabel_VJ")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.requireMesoLabel_VJ)
        self.finishDateLabel_VJ = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.finishDateLabel_VJ.setFont(font)
        self.finishDateLabel_VJ.setObjectName("finishDateLabel_VJ")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.finishDateLabel_VJ)
        self.remainDateLabel_VJ = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.remainDateLabel_VJ.setFont(font)
        self.remainDateLabel_VJ.setObjectName("remainDateLabel_VJ")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.remainDateLabel_VJ)
        self.requireMeso_VJ = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.requireMeso_VJ.setFont(font)
        self.requireMeso_VJ.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.requireMeso_VJ.setObjectName("requireMeso_VJ")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.requireMeso_VJ)
        self.remainDate_VJ = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.remainDate_VJ.setFont(font)
        self.remainDate_VJ.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.remainDate_VJ.setObjectName("remainDate_VJ")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.remainDate_VJ)
        self.finishDate_VJ = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.finishDate_VJ.setFont(font)
        self.finishDate_VJ.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.finishDate_VJ.setObjectName("finishDate_VJ")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.finishDate_VJ)
        self.quest_VJ = QtWidgets.QCheckBox(self.vanishingJourney)
        self.quest_VJ.setGeometry(QtCore.QRect(130, 120, 16, 19))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.quest_VJ.setFont(font)
        self.quest_VJ.setText("")
        self.quest_VJ.setChecked(True)
        self.quest_VJ.setObjectName("quest_VJ")
        self.spectrum = QtWidgets.QCheckBox(self.vanishingJourney)
        self.spectrum.setGeometry(QtCore.QRect(130, 150, 16, 19))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.spectrum.setFont(font)
        self.spectrum.setText("")
        self.spectrum.setObjectName("spectrum")
        self.questLabel_VJ = QtWidgets.QLabel(self.vanishingJourney)
        self.questLabel_VJ.setGeometry(QtCore.QRect(20, 120, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.questLabel_VJ.setFont(font)
        self.questLabel_VJ.setObjectName("questLabel_VJ")
        self.spectrumLabel = QtWidgets.QLabel(self.vanishingJourney)
        self.spectrumLabel.setGeometry(QtCore.QRect(20, 150, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.spectrumLabel.setFont(font)
        self.spectrumLabel.setObjectName("spectrumLabel")
        self.reverseCityLabel = QtWidgets.QLabel(self.vanishingJourney)
        self.reverseCityLabel.setGeometry(QtCore.QRect(20, 180, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.reverseCityLabel.setFont(font)
        self.reverseCityLabel.setObjectName("reverseCityLabel")
        self.reverseCity = QtWidgets.QCheckBox(self.vanishingJourney)
        self.reverseCity.setGeometry(QtCore.QRect(130, 180, 16, 19))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.reverseCity.setFont(font)
        self.reverseCity.setText("")
        self.reverseCity.setObjectName("reverseCity")
        self.vanishingJourneyImage = QtWidgets.QLabel(Dialog)
        self.vanishingJourneyImage.setGeometry(QtCore.QRect(0, 10, 61, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.vanishingJourneyImage.setFont(font)
        self.vanishingJourneyImage.setText("")
        self.vanishingJourneyImage.setPixmap(QtGui.QPixmap(":/ArcaneSymbol/VanishingJourney.png"))
        self.vanishingJourneyImage.setObjectName("vanishingJourneyImage")
        self.chuchuIslandImage = QtWidgets.QLabel(Dialog)
        self.chuchuIslandImage.setGeometry(QtCore.QRect(330, 10, 61, 51))
        
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.chuchuIslandImage.setFont(font)
        self.chuchuIslandImage.setText("")
        self.chuchuIslandImage.setPixmap(QtGui.QPixmap(":/ArcaneSymbol/ChuChuIsland.png"))
        self.chuchuIslandImage.setObjectName("chuchuIslandImage")
        self.chuchuIsland = QtWidgets.QGroupBox(Dialog)
        self.chuchuIsland.setGeometry(QtCore.QRect(360, 70, 301, 331))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.chuchuIsland.setFont(font)
        self.chuchuIsland.setObjectName("chuchuIsland")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.chuchuIsland)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(20, 30, 161, 57))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.formLayoutWidget_3.setFont(font)
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.currentLevelLabel_CCI = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.currentLevelLabel_CCI.setFont(font)
        self.currentLevelLabel_CCI.setObjectName("currentLevelLabel_CCI")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.currentLevelLabel_CCI)
        self.currentExpLabel_CCI = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.currentExpLabel_CCI.setFont(font)
        self.currentExpLabel_CCI.setObjectName("currentExpLabel_CCI")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.currentExpLabel_CCI)
        self.currentLevel_CCI = QtWidgets.QSpinBox(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.currentLevel_CCI.setFont(font)
        self.currentLevel_CCI.setObjectName("currentLevel_CCI")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.currentLevel_CCI)
        self.currentExp_CCI = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.currentExp_CCI.setFont(font)
        self.currentExp_CCI.setObjectName("currentExp_CCI")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.currentExp_CCI)
        self.expRatio_CCI = QtWidgets.QLabel(self.chuchuIsland)
        self.expRatio_CCI.setGeometry(QtCore.QRect(20, 90, 261, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.expRatio_CCI.setFont(font)
        self.expRatio_CCI.setAlignment(QtCore.Qt.AlignCenter)
        self.expRatio_CCI.setObjectName("expRatio_CCI")
        self.result_CCI = QtWidgets.QGroupBox(self.chuchuIsland)
        self.result_CCI.setGeometry(QtCore.QRect(10, 210, 281, 111))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.result_CCI.setFont(font)
        self.result_CCI.setObjectName("result_CCI")
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.result_CCI)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(10, 30, 261, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.formLayoutWidget_4.setFont(font)
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.requireMesoLabel_CCI = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.requireMesoLabel_CCI.setFont(font)
        self.requireMesoLabel_CCI.setObjectName("requireMesoLabel_CCI")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.requireMesoLabel_CCI)
        self.finishDateLabel_CCI = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.finishDateLabel_CCI.setFont(font)
        self.finishDateLabel_CCI.setObjectName("finishDateLabel_CCI")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.finishDateLabel_CCI)
        self.remainDateLabel_CCI = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.remainDateLabel_CCI.setFont(font)
        self.remainDateLabel_CCI.setObjectName("remainDateLabel_CCI")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.remainDateLabel_CCI)
        self.requireMeso_CCI = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.requireMeso_CCI.setFont(font)
        self.requireMeso_CCI.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.requireMeso_CCI.setObjectName("requireMeso_CCI")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.requireMeso_CCI)
        self.remainDate_CCI = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.remainDate_CCI.setFont(font)
        self.remainDate_CCI.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.remainDate_CCI.setObjectName("remainDate_CCI")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.remainDate_CCI)
        self.finishDate_CCI = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.finishDate_CCI.setFont(font)
        self.finishDate_CCI.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.finishDate_CCI.setObjectName("finishDate_CCI")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.finishDate_CCI)
        self.quest_CCI = QtWidgets.QCheckBox(self.chuchuIsland)
        self.quest_CCI.setGeometry(QtCore.QRect(130, 120, 16, 19))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.quest_CCI.setFont(font)
        self.quest_CCI.setText("")
        self.quest_CCI.setChecked(True)
        self.quest_CCI.setObjectName("quest_CCI")
        self.questLabel_CCI = QtWidgets.QLabel(self.chuchuIsland)
        self.questLabel_CCI.setGeometry(QtCore.QRect(20, 120, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.questLabel_CCI.setFont(font)
        self.questLabel_CCI.setObjectName("questLabel_CCI")
        self.hungryMutoLabel = QtWidgets.QLabel(self.chuchuIsland)
        self.hungryMutoLabel.setGeometry(QtCore.QRect(20, 150, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.hungryMutoLabel.setFont(font)
        self.hungryMutoLabel.setObjectName("hungryMutoLabel")
        self.hungryMuto = QtWidgets.QComboBox(self.chuchuIsland)
        self.hungryMuto.setGeometry(QtCore.QRect(130, 150, 94, 22))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.hungryMuto.setFont(font)
        self.hungryMuto.setEditable(False)
        self.hungryMuto.setPlaceholderText("")
        self.hungryMuto.setObjectName("hungryMuto")
        self.hungryMuto.addItem("")
        self.hungryMuto.addItem("")
        self.hungryMuto.addItem("")
        self.yumyumIslandLabel = QtWidgets.QLabel(self.chuchuIsland)
        self.yumyumIslandLabel.setGeometry(QtCore.QRect(20, 180, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.yumyumIslandLabel.setFont(font)
        self.yumyumIslandLabel.setObjectName("yumyumIslandLabel")
        self.yumyumIsland = QtWidgets.QCheckBox(self.chuchuIsland)
        self.yumyumIsland.setGeometry(QtCore.QRect(130, 180, 16, 19))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.yumyumIsland.setFont(font)
        self.yumyumIsland.setText("")
        self.yumyumIsland.setObjectName("yumyumIsland")
        self.lacheleinImage = QtWidgets.QLabel(Dialog)
        self.lacheleinImage.setGeometry(QtCore.QRect(650, 10, 61, 51))
        
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.lacheleinImage.setFont(font)
        self.lacheleinImage.setText("")
        self.lacheleinImage.setPixmap(QtGui.QPixmap(":/ArcaneSymbol/Lachelein.png"))
        self.lacheleinImage.setObjectName("lacheleinImage")
        self.lachelein = QtWidgets.QGroupBox(Dialog)
        self.lachelein.setGeometry(QtCore.QRect(670, 70, 301, 331))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.lachelein.setFont(font)
        self.lachelein.setObjectName("lachelein")
        self.formLayoutWidget_5 = QtWidgets.QWidget(self.lachelein)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(20, 30, 161, 57))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.formLayoutWidget_5.setFont(font)
        self.formLayoutWidget_5.setObjectName("formLayoutWidget_5")
        self.formLayout_5 = QtWidgets.QFormLayout(self.formLayoutWidget_5)
        self.formLayout_5.setContentsMargins(0, 0, 0, 0)
        self.formLayout_5.setObjectName("formLayout_5")
        self.currentLevelLabel_LC = QtWidgets.QLabel(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.currentLevelLabel_LC.setFont(font)
        self.currentLevelLabel_LC.setObjectName("currentLevelLabel_LC")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.currentLevelLabel_LC)
        self.currentExpLabel_LC = QtWidgets.QLabel(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.currentExpLabel_LC.setFont(font)
        self.currentExpLabel_LC.setObjectName("currentExpLabel_LC")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.currentExpLabel_LC)
        self.currentLevel_LC = QtWidgets.QSpinBox(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.currentLevel_LC.setFont(font)
        self.currentLevel_LC.setObjectName("currentLevel_LC")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.currentLevel_LC)
        self.currentExp_LC = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.currentExp_LC.setFont(font)
        self.currentExp_LC.setObjectName("currentExp_LC")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.currentExp_LC)
        self.expRatio_LC = QtWidgets.QLabel(self.lachelein)
        self.expRatio_LC.setGeometry(QtCore.QRect(20, 90, 261, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.expRatio_LC.setFont(font)
        self.expRatio_LC.setAlignment(QtCore.Qt.AlignCenter)
        self.expRatio_LC.setObjectName("expRatio_LC")
        self.result_LC = QtWidgets.QGroupBox(self.lachelein)
        self.result_LC.setGeometry(QtCore.QRect(10, 210, 281, 111))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.result_LC.setFont(font)
        self.result_LC.setObjectName("result_LC")
        self.formLayoutWidget_6 = QtWidgets.QWidget(self.result_LC)
        self.formLayoutWidget_6.setGeometry(QtCore.QRect(10, 30, 261, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.formLayoutWidget_6.setFont(font)
        self.formLayoutWidget_6.setObjectName("formLayoutWidget_6")
        self.formLayout_6 = QtWidgets.QFormLayout(self.formLayoutWidget_6)
        self.formLayout_6.setContentsMargins(0, 0, 0, 0)
        self.formLayout_6.setObjectName("formLayout_6")
        self.requireMesoLabel_LC = QtWidgets.QLabel(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.requireMesoLabel_LC.setFont(font)
        self.requireMesoLabel_LC.setObjectName("requireMesoLabel_LC")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.requireMesoLabel_LC)
        self.finishDateLabel_LC = QtWidgets.QLabel(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.finishDateLabel_LC.setFont(font)
        self.finishDateLabel_LC.setObjectName("finishDateLabel_LC")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.finishDateLabel_LC)
        self.remainDateLabel_LC = QtWidgets.QLabel(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.remainDateLabel_LC.setFont(font)
        self.remainDateLabel_LC.setObjectName("remainDateLabel_LC")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.remainDateLabel_LC)
        self.requireMeso_LC = QtWidgets.QLabel(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.requireMeso_LC.setFont(font)
        self.requireMeso_LC.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.requireMeso_LC.setObjectName("requireMeso_LC")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.requireMeso_LC)
        self.remainDate_LC = QtWidgets.QLabel(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.remainDate_LC.setFont(font)
        self.remainDate_LC.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.remainDate_LC.setObjectName("remainDate_LC")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.remainDate_LC)
        self.finishDate_LC = QtWidgets.QLabel(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.finishDate_LC.setFont(font)
        self.finishDate_LC.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.finishDate_LC.setObjectName("finishDate_LC")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.finishDate_LC)
        self.quest_LC = QtWidgets.QCheckBox(self.lachelein)
        self.quest_LC.setGeometry(QtCore.QRect(130, 120, 16, 19))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.quest_LC.setFont(font)
        self.quest_LC.setText("")
        self.quest_LC.setChecked(True)
        self.quest_LC.setObjectName("quest_LC")
        self.questLabel_LC = QtWidgets.QLabel(self.lachelein)
        self.questLabel_LC.setGeometry(QtCore.QRect(20, 120, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.questLabel_LC.setFont(font)
        self.questLabel_LC.setObjectName("questLabel_LC")
        self.dreamBreakerLabel = QtWidgets.QLabel(self.lachelein)
        self.dreamBreakerLabel.setGeometry(QtCore.QRect(20, 150, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.dreamBreakerLabel.setFont(font)
        self.dreamBreakerLabel.setObjectName("dreamBreakerLabel")
        self.dreamBreaker = QtWidgets.QLineEdit(self.lachelein)
        self.dreamBreaker.setGeometry(QtCore.QRect(130, 150, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.dreamBreaker.setFont(font)
        self.dreamBreaker.setObjectName("dreamBreaker")
        self.arcanaImage = QtWidgets.QLabel(Dialog)
        self.arcanaImage.setGeometry(QtCore.QRect(0, 420, 61, 51))
        
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.arcanaImage.setFont(font)
        self.arcanaImage.setText("")
        self.arcanaImage.setPixmap(QtGui.QPixmap(":/ArcaneSymbol/Arcana.png"))
        self.arcanaImage.setObjectName("arcanaImage")
        self.arcana = QtWidgets.QGroupBox(Dialog)
        self.arcana.setGeometry(QtCore.QRect(40, 470, 301, 331))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.arcana.setFont(font)
        self.arcana.setObjectName("arcana")
        self.formLayoutWidget_7 = QtWidgets.QWidget(self.arcana)
        self.formLayoutWidget_7.setGeometry(QtCore.QRect(20, 30, 161, 57))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.formLayoutWidget_7.setFont(font)
        self.formLayoutWidget_7.setObjectName("formLayoutWidget_7")
        self.formLayout_7 = QtWidgets.QFormLayout(self.formLayoutWidget_7)
        self.formLayout_7.setContentsMargins(0, 0, 0, 0)
        self.formLayout_7.setObjectName("formLayout_7")
        self.currentLevelLabel_AR = QtWidgets.QLabel(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.currentLevelLabel_AR.setFont(font)
        self.currentLevelLabel_AR.setObjectName("currentLevelLabel_AR")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.currentLevelLabel_AR)
        self.currentExpLabel_AR = QtWidgets.QLabel(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.currentExpLabel_AR.setFont(font)
        self.currentExpLabel_AR.setObjectName("currentExpLabel_AR")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.currentExpLabel_AR)
        self.currentLevel_AR = QtWidgets.QSpinBox(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.currentLevel_AR.setFont(font)
        self.currentLevel_AR.setObjectName("currentLevel_AR")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.currentLevel_AR)
        self.currentExp_AR = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.currentExp_AR.setFont(font)
        self.currentExp_AR.setObjectName("currentExp_AR")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.currentExp_AR)
        self.expRatio_AR = QtWidgets.QLabel(self.arcana)
        self.expRatio_AR.setGeometry(QtCore.QRect(20, 90, 261, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.expRatio_AR.setFont(font)
        self.expRatio_AR.setAlignment(QtCore.Qt.AlignCenter)
        self.expRatio_AR.setObjectName("expRatio_AR")
        self.result_AR = QtWidgets.QGroupBox(self.arcana)
        self.result_AR.setGeometry(QtCore.QRect(10, 210, 281, 111))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.result_AR.setFont(font)
        self.result_AR.setObjectName("result_AR")
        self.formLayoutWidget_8 = QtWidgets.QWidget(self.result_AR)
        self.formLayoutWidget_8.setGeometry(QtCore.QRect(10, 30, 261, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.formLayoutWidget_8.setFont(font)
        self.formLayoutWidget_8.setObjectName("formLayoutWidget_8")
        self.formLayout_8 = QtWidgets.QFormLayout(self.formLayoutWidget_8)
        self.formLayout_8.setContentsMargins(0, 0, 0, 0)
        self.formLayout_8.setObjectName("formLayout_8")
        self.requireMesoLabel_AR = QtWidgets.QLabel(self.formLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.requireMesoLabel_AR.setFont(font)
        self.requireMesoLabel_AR.setObjectName("requireMesoLabel_AR")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.requireMesoLabel_AR)
        self.finishDateLabel_AR = QtWidgets.QLabel(self.formLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.finishDateLabel_AR.setFont(font)
        self.finishDateLabel_AR.setObjectName("finishDateLabel_AR")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.finishDateLabel_AR)
        self.remainDateLabel_AR = QtWidgets.QLabel(self.formLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.remainDateLabel_AR.setFont(font)
        self.remainDateLabel_AR.setObjectName("remainDateLabel_AR")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.remainDateLabel_AR)
        self.requireMeso_AR = QtWidgets.QLabel(self.formLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.requireMeso_AR.setFont(font)
        self.requireMeso_AR.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.requireMeso_AR.setObjectName("requireMeso_AR")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.requireMeso_AR)
        self.remainDate_AR = QtWidgets.QLabel(self.formLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.remainDate_AR.setFont(font)
        self.remainDate_AR.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.remainDate_AR.setObjectName("remainDate_AR")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.remainDate_AR)
        self.finishDate_AR = QtWidgets.QLabel(self.formLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.finishDate_AR.setFont(font)
        self.finishDate_AR.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.finishDate_AR.setObjectName("finishDate_AR")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.finishDate_AR)
        self.quest_AR = QtWidgets.QCheckBox(self.arcana)
        self.quest_AR.setGeometry(QtCore.QRect(130, 120, 16, 19))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.quest_AR.setFont(font)
        self.quest_AR.setText("")
        self.quest_AR.setChecked(True)
        self.quest_AR.setObjectName("quest_AR")
        self.questLabel_AR = QtWidgets.QLabel(self.arcana)
        self.questLabel_AR.setGeometry(QtCore.QRect(20, 120, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.questLabel_AR.setFont(font)
        self.questLabel_AR.setObjectName("questLabel_AR")
        self.spiritSaviorLabel = QtWidgets.QLabel(self.arcana)
        self.spiritSaviorLabel.setGeometry(QtCore.QRect(20, 150, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.spiritSaviorLabel.setFont(font)
        self.spiritSaviorLabel.setObjectName("spiritSaviorLabel")
        self.spiritSavior = QtWidgets.QLineEdit(self.arcana)
        self.spiritSavior.setGeometry(QtCore.QRect(130, 150, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.spiritSavior.setFont(font)
        self.spiritSavior.setObjectName("spiritSavior")
        self.morassImage = QtWidgets.QLabel(Dialog)
        self.morassImage.setGeometry(QtCore.QRect(330, 420, 61, 51))
        
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.morassImage.setFont(font)
        self.morassImage.setText("")
        self.morassImage.setPixmap(QtGui.QPixmap(":/ArcaneSymbol/Morass.png"))
        self.morassImage.setObjectName("morassImage")
        self.morass = QtWidgets.QGroupBox(Dialog)
        self.morass.setGeometry(QtCore.QRect(360, 470, 291, 331))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.morass.setFont(font)
        self.morass.setObjectName("morass")
        self.formLayoutWidget_13 = QtWidgets.QWidget(self.morass)
        self.formLayoutWidget_13.setGeometry(QtCore.QRect(20, 30, 161, 57))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.formLayoutWidget_13.setFont(font)
        self.formLayoutWidget_13.setObjectName("formLayoutWidget_13")
        self.formLayout_13 = QtWidgets.QFormLayout(self.formLayoutWidget_13)
        self.formLayout_13.setContentsMargins(0, 0, 0, 0)
        self.formLayout_13.setObjectName("formLayout_13")
        self.currentLevelLabel_MR = QtWidgets.QLabel(self.formLayoutWidget_13)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.currentLevelLabel_MR.setFont(font)
        self.currentLevelLabel_MR.setObjectName("currentLevelLabel_MR")
        self.formLayout_13.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.currentLevelLabel_MR)
        self.currentExpLabel_MR = QtWidgets.QLabel(self.formLayoutWidget_13)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.currentExpLabel_MR.setFont(font)
        self.currentExpLabel_MR.setObjectName("currentExpLabel_MR")
        self.formLayout_13.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.currentExpLabel_MR)
        self.currentLevel_MR = QtWidgets.QSpinBox(self.formLayoutWidget_13)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.currentLevel_MR.setFont(font)
        self.currentLevel_MR.setObjectName("currentLevel_MR")
        self.formLayout_13.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.currentLevel_MR)
        self.currentExp_MR = QtWidgets.QLineEdit(self.formLayoutWidget_13)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.currentExp_MR.setFont(font)
        self.currentExp_MR.setObjectName("currentExp_MR")
        self.formLayout_13.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.currentExp_MR)
        self.expRatio_MR = QtWidgets.QLabel(self.morass)
        self.expRatio_MR.setGeometry(QtCore.QRect(20, 90, 251, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.expRatio_MR.setFont(font)
        self.expRatio_MR.setAlignment(QtCore.Qt.AlignCenter)
        self.expRatio_MR.setObjectName("expRatio_MR")
        self.result_MR = QtWidgets.QGroupBox(self.morass)
        self.result_MR.setGeometry(QtCore.QRect(10, 210, 271, 111))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.result_MR.setFont(font)
        self.result_MR.setObjectName("result_MR")
        self.formLayoutWidget_14 = QtWidgets.QWidget(self.result_MR)
        self.formLayoutWidget_14.setGeometry(QtCore.QRect(10, 30, 251, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.formLayoutWidget_14.setFont(font)
        self.formLayoutWidget_14.setObjectName("formLayoutWidget_14")
        self.formLayout_14 = QtWidgets.QFormLayout(self.formLayoutWidget_14)
        self.formLayout_14.setContentsMargins(0, 0, 0, 0)
        self.formLayout_14.setObjectName("formLayout_14")
        self.requireMesoLabel_MR = QtWidgets.QLabel(self.formLayoutWidget_14)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.requireMesoLabel_MR.setFont(font)
        self.requireMesoLabel_MR.setObjectName("requireMesoLabel_MR")
        self.formLayout_14.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.requireMesoLabel_MR)
        self.finishDateLabel_MR = QtWidgets.QLabel(self.formLayoutWidget_14)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.finishDateLabel_MR.setFont(font)
        self.finishDateLabel_MR.setObjectName("finishDateLabel_MR")
        self.formLayout_14.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.finishDateLabel_MR)
        self.remainDateLabel_MR = QtWidgets.QLabel(self.formLayoutWidget_14)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.remainDateLabel_MR.setFont(font)
        self.remainDateLabel_MR.setObjectName("remainDateLabel_MR")
        self.formLayout_14.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.remainDateLabel_MR)
        self.requireMeso_MR = QtWidgets.QLabel(self.formLayoutWidget_14)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.requireMeso_MR.setFont(font)
        self.requireMeso_MR.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.requireMeso_MR.setObjectName("requireMeso_MR")
        self.formLayout_14.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.requireMeso_MR)
        self.remainDate_MR = QtWidgets.QLabel(self.formLayoutWidget_14)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.remainDate_MR.setFont(font)
        self.remainDate_MR.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.remainDate_MR.setObjectName("remainDate_MR")
        self.formLayout_14.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.remainDate_MR)
        self.finishDate_MR = QtWidgets.QLabel(self.formLayoutWidget_14)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.finishDate_MR.setFont(font)
        self.finishDate_MR.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.finishDate_MR.setObjectName("finishDate_MR")
        self.formLayout_14.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.finishDate_MR)
        self.quest_MR = QtWidgets.QCheckBox(self.morass)
        self.quest_MR.setGeometry(QtCore.QRect(130, 120, 16, 19))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.quest_MR.setFont(font)
        self.quest_MR.setText("")
        self.quest_MR.setChecked(True)
        self.quest_MR.setObjectName("quest_MR")
        self.questLabel_MR = QtWidgets.QLabel(self.morass)
        self.questLabel_MR.setGeometry(QtCore.QRect(20, 120, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.questLabel_MR.setFont(font)
        self.questLabel_MR.setObjectName("questLabel_MR")
        self.esferaImage = QtWidgets.QLabel(Dialog)
        self.esferaImage.setGeometry(QtCore.QRect(650, 420, 61, 51))
        
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.esferaImage.setFont(font)
        self.esferaImage.setText("")
        self.esferaImage.setPixmap(QtGui.QPixmap(":/ArcaneSymbol/Esfera.png"))
        self.esferaImage.setObjectName("esferaImage")
        self.esfera = QtWidgets.QGroupBox(Dialog)
        self.esfera.setGeometry(QtCore.QRect(670, 470, 301, 331))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.esfera.setFont(font)
        self.esfera.setObjectName("esfera")
        self.formLayoutWidget_15 = QtWidgets.QWidget(self.esfera)
        self.formLayoutWidget_15.setGeometry(QtCore.QRect(20, 30, 161, 57))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.formLayoutWidget_15.setFont(font)
        self.formLayoutWidget_15.setObjectName("formLayoutWidget_15")
        self.formLayout_15 = QtWidgets.QFormLayout(self.formLayoutWidget_15)
        self.formLayout_15.setContentsMargins(0, 0, 0, 0)
        self.formLayout_15.setObjectName("formLayout_15")
        self.currentLevelLabel_ES = QtWidgets.QLabel(self.formLayoutWidget_15)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.currentLevelLabel_ES.setFont(font)
        self.currentLevelLabel_ES.setObjectName("currentLevelLabel_ES")
        self.formLayout_15.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.currentLevelLabel_ES)
        self.currentExpLabel_ES = QtWidgets.QLabel(self.formLayoutWidget_15)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.currentExpLabel_ES.setFont(font)
        self.currentExpLabel_ES.setObjectName("currentExpLabel_ES")
        self.formLayout_15.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.currentExpLabel_ES)
        self.currentLevel_ES = QtWidgets.QSpinBox(self.formLayoutWidget_15)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.currentLevel_ES.setFont(font)
        self.currentLevel_ES.setObjectName("currentLevel_ES")
        self.formLayout_15.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.currentLevel_ES)
        self.currentExp_ES = QtWidgets.QLineEdit(self.formLayoutWidget_15)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.currentExp_ES.setFont(font)
        self.currentExp_ES.setObjectName("currentExp_ES")
        self.formLayout_15.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.currentExp_ES)
        self.expRatio_ES = QtWidgets.QLabel(self.esfera)
        self.expRatio_ES.setGeometry(QtCore.QRect(20, 90, 261, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.expRatio_ES.setFont(font)
        self.expRatio_ES.setAlignment(QtCore.Qt.AlignCenter)
        self.expRatio_ES.setObjectName("expRatio_ES")
        self.result_ES = QtWidgets.QGroupBox(self.esfera)
        self.result_ES.setGeometry(QtCore.QRect(10, 210, 281, 111))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.result_ES.setFont(font)
        self.result_ES.setObjectName("result_ES")
        self.formLayoutWidget_16 = QtWidgets.QWidget(self.result_ES)
        self.formLayoutWidget_16.setGeometry(QtCore.QRect(10, 30, 261, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.formLayoutWidget_16.setFont(font)
        self.formLayoutWidget_16.setObjectName("formLayoutWidget_16")
        self.formLayout_16 = QtWidgets.QFormLayout(self.formLayoutWidget_16)
        self.formLayout_16.setContentsMargins(0, 0, 0, 0)
        self.formLayout_16.setObjectName("formLayout_16")
        self.requireMesoLabel_ES = QtWidgets.QLabel(self.formLayoutWidget_16)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.requireMesoLabel_ES.setFont(font)
        self.requireMesoLabel_ES.setObjectName("requireMesoLabel_ES")
        self.formLayout_16.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.requireMesoLabel_ES)
        self.finishDateLabel_ES = QtWidgets.QLabel(self.formLayoutWidget_16)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.finishDateLabel_ES.setFont(font)
        self.finishDateLabel_ES.setObjectName("finishDateLabel_ES")
        self.formLayout_16.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.finishDateLabel_ES)
        self.remainDateLabel_ES = QtWidgets.QLabel(self.formLayoutWidget_16)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.remainDateLabel_ES.setFont(font)
        self.remainDateLabel_ES.setObjectName("remainDateLabel_ES")
        self.formLayout_16.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.remainDateLabel_ES)
        self.requireMeso_ES = QtWidgets.QLabel(self.formLayoutWidget_16)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.requireMeso_ES.setFont(font)
        self.requireMeso_ES.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.requireMeso_ES.setObjectName("requireMeso_ES")
        self.formLayout_16.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.requireMeso_ES)
        self.remainDate_ES = QtWidgets.QLabel(self.formLayoutWidget_16)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.remainDate_ES.setFont(font)
        self.remainDate_ES.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.remainDate_ES.setObjectName("remainDate_ES")
        self.formLayout_16.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.remainDate_ES)
        self.finishDate_ES = QtWidgets.QLabel(self.formLayoutWidget_16)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.finishDate_ES.setFont(font)
        self.finishDate_ES.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.finishDate_ES.setObjectName("finishDate_ES")
        self.formLayout_16.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.finishDate_ES)
        self.quest_ES = QtWidgets.QCheckBox(self.esfera)
        self.quest_ES.setGeometry(QtCore.QRect(130, 120, 16, 19))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.quest_ES.setFont(font)
        self.quest_ES.setText("")
        self.quest_ES.setChecked(True)
        self.quest_ES.setObjectName("quest_ES")
        self.questLabel_ES = QtWidgets.QLabel(self.esfera)
        self.questLabel_ES.setGeometry(QtCore.QRect(20, 120, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.questLabel_ES.setFont(font)
        self.questLabel_ES.setObjectName("questLabel_ES")
        
        self.cerniumImage = QtWidgets.QLabel(Dialog)
        self.cerniumImage.setGeometry(QtCore.QRect(990, 40, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.cerniumImage.setFont(font)
        self.cerniumImage.setText("")
        self.cerniumImage.setPixmap(QtGui.QPixmap(":/AuthenticForce/Cernium.png"))
        self.cerniumImage.setObjectName("cerniumImage")
        self.cernium = QtWidgets.QGroupBox(Dialog)
        self.cernium.setGeometry(QtCore.QRect(1010, 70, 301, 331))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.cernium.setFont(font)
        self.cernium.setObjectName("cernium")
        self.formLayoutWidget_17 = QtWidgets.QWidget(self.cernium)
        self.formLayoutWidget_17.setGeometry(QtCore.QRect(20, 30, 161, 57))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.formLayoutWidget_17.setFont(font)
        self.formLayoutWidget_17.setObjectName("formLayoutWidget_17")
        self.formLayout_17 = QtWidgets.QFormLayout(self.formLayoutWidget_17)
        self.formLayout_17.setContentsMargins(0, 0, 0, 0)
        self.formLayout_17.setObjectName("formLayout_17")
        self.currentLevelLabel_CR = QtWidgets.QLabel(self.formLayoutWidget_17)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.currentLevelLabel_CR.setFont(font)
        self.currentLevelLabel_CR.setObjectName("currentLevelLabel_CR")
        self.formLayout_17.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.currentLevelLabel_CR)
        self.currentExpLabel_CR = QtWidgets.QLabel(self.formLayoutWidget_17)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.currentExpLabel_CR.setFont(font)
        self.currentExpLabel_CR.setObjectName("currentExpLabel_CR")
        self.formLayout_17.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.currentExpLabel_CR)
        self.currentLevel_CR = QtWidgets.QSpinBox(self.formLayoutWidget_17)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.currentLevel_CR.setFont(font)
        self.currentLevel_CR.setObjectName("currentLevel_CR")
        self.formLayout_17.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.currentLevel_CR)
        self.currentExp_CR = QtWidgets.QLineEdit(self.formLayoutWidget_17)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.currentExp_CR.setFont(font)
        self.currentExp_CR.setObjectName("currentExp_CR")
        self.formLayout_17.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.currentExp_CR)
        self.expRatio_CR = QtWidgets.QLabel(self.cernium)
        self.expRatio_CR.setGeometry(QtCore.QRect(20, 90, 261, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.expRatio_CR.setFont(font)
        self.expRatio_CR.setAlignment(QtCore.Qt.AlignCenter)
        self.expRatio_CR.setObjectName("expRatio_CR")
        self.result_CR = QtWidgets.QGroupBox(self.cernium)
        self.result_CR.setGeometry(QtCore.QRect(10, 210, 281, 111))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.result_CR.setFont(font)
        self.result_CR.setObjectName("result_CR")
        self.formLayoutWidget_18 = QtWidgets.QWidget(self.result_CR)
        self.formLayoutWidget_18.setGeometry(QtCore.QRect(10, 30, 261, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.formLayoutWidget_18.setFont(font)
        self.formLayoutWidget_18.setObjectName("formLayoutWidget_18")
        self.formLayout_18 = QtWidgets.QFormLayout(self.formLayoutWidget_18)
        self.formLayout_18.setContentsMargins(0, 0, 0, 0)
        self.formLayout_18.setObjectName("formLayout_18")
        self.requireMesoLabel_CR = QtWidgets.QLabel(self.formLayoutWidget_18)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.requireMesoLabel_CR.setFont(font)
        self.requireMesoLabel_CR.setObjectName("requireMesoLabel_CR")
        self.formLayout_18.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.requireMesoLabel_CR)
        self.finishDateLabel_CR = QtWidgets.QLabel(self.formLayoutWidget_18)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.finishDateLabel_CR.setFont(font)
        self.finishDateLabel_CR.setObjectName("finishDateLabel_CR")
        self.formLayout_18.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.finishDateLabel_CR)
        self.remainDateLabel_CR = QtWidgets.QLabel(self.formLayoutWidget_18)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.remainDateLabel_CR.setFont(font)
        self.remainDateLabel_CR.setObjectName("remainDateLabel_CR")
        self.formLayout_18.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.remainDateLabel_CR)
        self.requireMeso_CR = QtWidgets.QLabel(self.formLayoutWidget_18)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.requireMeso_CR.setFont(font)
        self.requireMeso_CR.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.requireMeso_CR.setObjectName("requireMeso_CR")
        self.formLayout_18.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.requireMeso_CR)
        self.remainDate_CR = QtWidgets.QLabel(self.formLayoutWidget_18)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.remainDate_CR.setFont(font)
        self.remainDate_CR.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.remainDate_CR.setObjectName("remainDate_CR")
        self.formLayout_18.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.remainDate_CR)
        self.finishDate_CR = QtWidgets.QLabel(self.formLayoutWidget_18)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.finishDate_CR.setFont(font)
        self.finishDate_CR.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.finishDate_CR.setObjectName("finishDate_CR")
        self.formLayout_18.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.finishDate_CR)
        self.quest_CR = QtWidgets.QCheckBox(self.cernium)
        self.quest_CR.setGeometry(QtCore.QRect(130, 120, 16, 19))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.quest_CR.setFont(font)
        self.quest_CR.setText("")
        self.quest_CR.setChecked(True)
        self.quest_CR.setObjectName("quest_CR")
        self.questLabelCR = QtWidgets.QLabel(self.cernium)
        self.questLabelCR.setGeometry(QtCore.QRect(20, 120, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.questLabelCR.setFont(font)
        self.questLabelCR.setObjectName("questLabelCR")
        
        self.hotelArcs = QtWidgets.QGroupBox(Dialog)
        self.hotelArcs.setGeometry(QtCore.QRect(1010, 470, 301, 331))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.hotelArcs.setFont(font)
        self.hotelArcs.setObjectName("hotelArcs")
        self.formLayoutWidget_19 = QtWidgets.QWidget(self.hotelArcs)
        self.formLayoutWidget_19.setGeometry(QtCore.QRect(20, 30, 161, 57))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.formLayoutWidget_19.setFont(font)
        self.formLayoutWidget_19.setObjectName("formLayoutWidget_19")
        self.formLayout_19 = QtWidgets.QFormLayout(self.formLayoutWidget_19)
        self.formLayout_19.setContentsMargins(0, 0, 0, 0)
        self.formLayout_19.setObjectName("formLayout_19")
        self.currentLevelLabel_HA = QtWidgets.QLabel(self.formLayoutWidget_19)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.currentLevelLabel_HA.setFont(font)
        self.currentLevelLabel_HA.setObjectName("currentLevelLabel_HA")
        self.formLayout_19.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.currentLevelLabel_HA)
        self.currentExpLabel_HA = QtWidgets.QLabel(self.formLayoutWidget_19)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.currentExpLabel_HA.setFont(font)
        self.currentExpLabel_HA.setObjectName("currentExpLabel_HA")
        self.formLayout_19.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.currentExpLabel_HA)
        self.currentLevel_HA = QtWidgets.QSpinBox(self.formLayoutWidget_19)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.currentLevel_HA.setFont(font)
        self.currentLevel_HA.setObjectName("currentLevel_HA")
        self.formLayout_19.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.currentLevel_HA)
        self.currentExp_HA = QtWidgets.QLineEdit(self.formLayoutWidget_19)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.currentExp_HA.setFont(font)
        self.currentExp_HA.setObjectName("currentExp_HA")
        self.formLayout_19.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.currentExp_HA)
        self.expRatio_HA = QtWidgets.QLabel(self.hotelArcs)
        self.expRatio_HA.setGeometry(QtCore.QRect(20, 90, 261, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.expRatio_HA.setFont(font)
        self.expRatio_HA.setAlignment(QtCore.Qt.AlignCenter)
        self.expRatio_HA.setObjectName("expRatio_HA")
        self.result_HA = QtWidgets.QGroupBox(self.hotelArcs)
        self.result_HA.setGeometry(QtCore.QRect(10, 210, 281, 111))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.result_HA.setFont(font)
        self.result_HA.setObjectName("result_HA")
        self.formLayoutWidget_20 = QtWidgets.QWidget(self.result_HA)
        self.formLayoutWidget_20.setGeometry(QtCore.QRect(10, 30, 261, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.formLayoutWidget_20.setFont(font)
        self.formLayoutWidget_20.setObjectName("formLayoutWidget_20")
        self.formLayout_20 = QtWidgets.QFormLayout(self.formLayoutWidget_20)
        self.formLayout_20.setContentsMargins(0, 0, 0, 0)
        self.formLayout_20.setObjectName("formLayout_20")
        self.requireMesoLabel_HA = QtWidgets.QLabel(self.formLayoutWidget_20)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.requireMesoLabel_HA.setFont(font)
        self.requireMesoLabel_HA.setObjectName("requireMesoLabel_HA")
        self.formLayout_20.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.requireMesoLabel_HA)
        self.finishDateLabel_HA = QtWidgets.QLabel(self.formLayoutWidget_20)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.finishDateLabel_HA.setFont(font)
        self.finishDateLabel_HA.setObjectName("finishDateLabel_HA")
        self.formLayout_20.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.finishDateLabel_HA)
        self.remainDateLabel_HA = QtWidgets.QLabel(self.formLayoutWidget_20)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.remainDateLabel_HA.setFont(font)
        self.remainDateLabel_HA.setObjectName("remainDateLabel_HA")
        self.formLayout_20.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.remainDateLabel_HA)
        self.requireMeso_HA = QtWidgets.QLabel(self.formLayoutWidget_20)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.requireMeso_HA.setFont(font)
        self.requireMeso_HA.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.requireMeso_HA.setObjectName("requireMeso_HA")
        self.formLayout_20.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.requireMeso_HA)
        self.remainDate_HA = QtWidgets.QLabel(self.formLayoutWidget_20)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.remainDate_HA.setFont(font)
        self.remainDate_HA.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.remainDate_HA.setObjectName("remainDate_HA")
        self.formLayout_20.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.remainDate_HA)
        self.finishDate_HA = QtWidgets.QLabel(self.formLayoutWidget_20)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.finishDate_HA.setFont(font)
        self.finishDate_HA.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.finishDate_HA.setObjectName("finishDate_HA")
        self.formLayout_20.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.finishDate_HA)
        self.quest_HA = QtWidgets.QCheckBox(self.hotelArcs)
        self.quest_HA.setGeometry(QtCore.QRect(130, 120, 16, 19))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.quest_HA.setFont(font)
        self.quest_HA.setText("")
        self.quest_HA.setChecked(True)
        self.quest_HA.setObjectName("quest_HA")
        self.questLabel_HA = QtWidgets.QLabel(self.hotelArcs)
        self.questLabel_HA.setGeometry(QtCore.QRect(20, 120, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.questLabel_HA.setFont(font)
        self.questLabel_HA.setObjectName("questLabel_HA")
        self.hotelArcsImage = QtWidgets.QLabel(Dialog)
        self.hotelArcsImage.setGeometry(QtCore.QRect(990, 440, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.hotelArcsImage.setFont(font)
        self.hotelArcsImage.setText("")
        self.hotelArcsImage.setPixmap(QtGui.QPixmap(":/AuthenticForce/HotelArcs.png"))
        self.hotelArcsImage.setObjectName("hotelArcsImage")

        self.retranslateUi(Dialog)
        self.hungryMuto.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        #PyQt Text Changed Functions
        self.currentExp_VJ.textChanged.connect(self.calcVanishingJourney)
        self.currentExp_CCI.textChanged.connect(self.calcChuchuIsland)
        self.currentExp_LC.textChanged.connect(self.calcLachelein)
        self.currentExp_AR.textChanged.connect(self.calcArcana)
        self.currentExp_MR.textChanged.connect(self.calcMorass)
        self.currentExp_ES.textChanged.connect(self.calcEsfera)
        self.currentExp_CR.textChanged.connect(self.calcCernium)
        self.currentExp_HA.textChanged.connect(self.calcHotelArcs)

    #Region Functions
        
    #Vanishing Journey    
    def calcVanishingJourney(self):
        currentLevel_VJ = int(self.currentLevel_VJ.text())
        currentExp_VJ = int(self.currentExp_VJ.text())
        requireExp_VJ = symbolRequireExpList[currentLevel_VJ - 1]
        requireMeso_VJ = sum(requireMesoList_VJ[currentLevel_VJ-1:])
        requireSymbol_VJ = sum(symbolRequireExpList[currentLevel_VJ:]) + (symbolRequireExpList[currentLevel_VJ-1] - currentExp_VJ)
        
        dailySymbol_VJ = 0
        if self.quest_VJ.isChecked() == True:
            if self.reverseCity.isChecked() == True:
                dailySymbol_VJ += 16
            else:
                dailySymbol_VJ += 8
        if self.spectrum.isChecked() == True:
            dailySymbol_VJ += 6
        
        self.expRatio_VJ.setText(str(currentExp_VJ) + " / " + str(requireExp_VJ) + "(" + str(int(currentExp_VJ / requireExp_VJ * 100)) + "%)")
        self.requireMeso_VJ.setText(str(format(requireMeso_VJ, ',') + " meso"))
        
        if dailySymbol_VJ != 0:
            dayLeft = int(requireSymbol_VJ/dailySymbol_VJ) + 1
            self.remainDate_VJ.setText(str(dayLeft)+ " days left")
            self.finishDate_VJ.setText(str(today + datetime.timedelta(days=dayLeft)))

    #Chu Chu Island   
    def calcChuchuIsland(self):
        currentLevel_CCI = int(self.currentLevel_CCI.text())
        currentExp_CCI = int(self.currentExp_CCI.text())
        requireExp_CCI = symbolRequireExpList[currentLevel_CCI - 1]
        requireMeso_CCI = sum(requireMesoList[currentLevel_CCI-1:])
        requireSymbol_CCI = sum(symbolRequireExpList[currentLevel_CCI:]) + (symbolRequireExpList[currentLevel_CCI-1] - currentExp_CCI)
        
        dailySymbol_CCI = 0
        if self.quest_CCI.isChecked() == True:
            if self.yumyumIsland.isChecked() == True:
                dailySymbol_CCI += 4
            else:
                dailySymbol_CCI += 8

        if self.hungryMuto.currentText() == "Easy":
            dailySymbol_CCI += 3
        elif self.hungryMuto.currentText() == "Normal":
            dailySymbol_CCI += 9
        elif self.hungryMuto.currentText() == "Hard":
            dailySymbol_CCI += 15
        
        self.expRatio_CCI.setText(str(currentExp_CCI) + " / " + str(requireExp_CCI) + "(" + str(int(currentExp_CCI / requireExp_CCI * 100)) + "%)")
        self.requireMeso_CCI.setText(str(format(requireMeso_CCI, ',') + " meso"))
        
        if dailySymbol_CCI != 0:
            dayLeft = int(requireSymbol_CCI/dailySymbol_CCI) + 1
            self.remainDate_CCI.setText(str(dayLeft)+ " days left")
            self.finishDate_CCI.setText(str(today + datetime.timedelta(days=dayLeft)))

    #Lachelein
    def calcLachelein(self):
        currentLevel_LC = int(self.currentLevel_LC.text())
        currentExp_LC = int(self.currentExp_LC.text())
        requireExp_LC = symbolRequireExpList[currentLevel_LC - 1]
        requireMeso_LC = sum(requireMesoList[currentLevel_LC-1:])
        requireSymbol_LC = sum(symbolRequireExpList[currentLevel_LC:]) + (symbolRequireExpList[currentLevel_LC-1] - currentExp_LC)
        
        dailySymbol_LC = 0
        if self.quest_LC.isChecked() == True:
            dailySymbol_LC += 4

        dreamCoin = int(self.dreamBreaker.text())
        dailySymbol_LC += (dreamCoin % 30)
        
        self.expRatio_LC.setText(str(currentExp_LC) + " / " + str(requireExp_LC) + "(" + str(int(currentExp_LC / requireExp_LC * 100)) + "%)")
        self.requireMeso_LC.setText(str(format(requireMeso_LC, ',') + " meso"))
        
        if dailySymbol_LC != 0:
            dayLeft = int(requireSymbol_LC/dailySymbol_LC) + 1
            self.remainDate_LC.setText(str(dayLeft)+ " days left")
            self.finishDate_LC.setText(str(today + datetime.timedelta(days=dayLeft)))

    #Arcana
    def calcArcana(self):
        currentLevel_AR = int(self.currentLevel_AR.text())
        currentExp_AR = int(self.currentExp_AR.text())
        requireExp_AR = symbolRequireExpList[currentLevel_AR - 1]
        requireMeso_AR = sum(requireMesoList[currentLevel_AR-1:])
        requireSymbol_AR = sum(symbolRequireExpList[currentLevel_AR:]) + (symbolRequireExpList[currentLevel_AR-1] - currentExp_AR)
        
        dailySymbol_AR = 0
        if self.quest_AR.isChecked() == True:
            dailySymbol_AR += 8

        spiritSaviorSymbol = int(self.spiritSavior.text())
        dailySymbol_AR += spiritSaviorSymbol

        
        self.expRatio_AR.setText(str(currentExp_AR) + " / " + str(requireExp_AR) + "(" + str(int(currentExp_AR / requireExp_AR * 100)) + "%)")
        self.requireMeso_AR.setText(str(format(requireMeso_AR, ',') + " meso"))
        
        if dailySymbol_AR != 0:
            dayLeft = int(requireSymbol_AR/dailySymbol_AR) + 1
            self.remainDate_AR.setText(str(dayLeft)+ " days left")
            self.finishDate_AR.setText(str(today + datetime.timedelta(days=dayLeft)))

    #Morass
    def calcMorass(self):
        currentLevel_MR = int(self.currentLevel_MR.text())
        currentExp_MR = int(self.currentExp_MR.text())
        requireExp_MR = symbolRequireExpList[currentLevel_MR - 1]
        requireMeso_MR = sum(requireMesoList[currentLevel_MR-1:])
        requireSymbol_MR = sum(symbolRequireExpList[currentLevel_MR:]) + (symbolRequireExpList[currentLevel_MR-1] - currentExp_MR)
        
        dailySymbol_MR = 0
        if self.quest_MR.isChecked() == True:
            dailySymbol_MR += 8
        
        self.expRatio_MR.setText(str(currentExp_MR) + " / " + str(requireExp_MR) + "(" + str(int(currentExp_MR / requireExp_MR * 100)) + "%)")
        self.requireMeso_MR.setText(str(format(requireMeso_MR, ',') + " meso"))
        
        if dailySymbol_MR != 0:
            dayLeft = int(requireSymbol_MR/dailySymbol_MR) + 1
            self.remainDate_MR.setText(str(dayLeft)+ " days left")
            self.finishDate_MR.setText(str(today + datetime.timedelta(days=dayLeft)))

    #Esfera
    def calcEsfera(self):
        currentLevel_ES = int(self.currentLevel_ES.text())
        currentExp_ES = int(self.currentExp_ES.text())
        requireExp_ES = symbolRequireExpList[currentLevel_ES - 1]
        requireMeso_ES = sum(requireMesoList[currentLevel_ES-1:])
        requireSymbol_ES = sum(symbolRequireExpList[currentLevel_ES:]) + (symbolRequireExpList[currentLevel_ES-1] - currentExp_ES)
        
        dailySymbol_ES = 0
        if self.quest_ES.isChecked() == True:
            dailySymbol_ES += 8
        
        self.expRatio_ES.setText(str(currentExp_ES) + " / " + str(requireExp_ES) + "(" + str(int(currentExp_ES / requireExp_ES * 100)) + "%)")
        self.requireMeso_ES.setText(str(format(requireMeso_ES, ',') + " meso"))
        
        if dailySymbol_ES != 0:
            dayLeft = int(requireSymbol_ES/dailySymbol_ES) + 1
            self.remainDate_ES.setText(str(dayLeft)+ " days left")
            self.finishDate_ES.setText(str(today + datetime.timedelta(days=dayLeft)))

    #Cernium
    def calcCernium(self):
        currentLevel_CR = int(self.currentLevel_CR.text())
        currentExp_CR = int(self.currentExp_CR.text())
        requireExp_CR = forceRequireExpList[currentLevel_CR - 1]
        requireMeso_CR = sum(requireMesoListForce[currentLevel_CR-1:])
        requireSymbol_CR = sum(forceRequireExpList[currentLevel_CR:]) + (forceRequireExpList[currentLevel_CR-1] - currentExp_CR)
        
        dailySymbol_CR = 0
        if self.quest_CR.isChecked() == True:
            dailySymbol_CR += 10
        
        self.expRatio_CR.setText(str(currentExp_CR) + " / " + str(requireExp_CR) + "(" + str(int(currentExp_CR / requireExp_CR * 100)) + "%)")
        self.requireMeso_CR.setText(str(format(requireMeso_CR, ',') + " meso"))
        
        if dailySymbol_CR != 0:
            dayLeft = int(requireSymbol_CR/dailySymbol_CR) + 1
            self.remainDate_CR.setText(str(dayLeft)+ " days left")
            self.finishDate_CR.setText(str(today + datetime.timedelta(days=dayLeft)))

    #Hotel Arcs
    def calcHotelArcs(self):
        currentLevel_HA = int(self.currentLevel_HA.text())
        currentExp_HA = int(self.currentExp_HA.text())
        requireExp_HA = forceRequireExpList[currentLevel_HA - 1]
        requireMeso_HA = sum(requireMesoListForce[currentLevel_HA-1:])
        requireSymbol_HA = sum(forceRequireExpList[currentLevel_HA:]) + (forceRequireExpList[currentLevel_HA-1] - currentExp_HA)
        
        dailySymbol_HA = 0
        if self.quest_HA.isChecked() == True:
            dailySymbol_HA += 10
        
        self.expRatio_HA.setText(str(currentExp_HA) + " / " + str(requireExp_HA) + "(" + str(int(currentExp_HA / requireExp_HA * 100)) + "%)")
        self.requireMeso_VJ.setText(str(format(requireMeso_HA, ',') + " meso"))
        
        if dailySymbol_HA != 0:
            dayLeft = int(requireSymbol_HA/dailySymbol_HA) + 1
            self.remainDate_HA.setText(str(dayLeft)+ " days left")
            self.finishDate_HA.setText(str(today + datetime.timedelta(days=dayLeft)))
    


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.vanishingJourney.setTitle(_translate("Dialog", "Vanishing Journey"))
        self.currentLevelLabel_VJ.setText(_translate("Dialog", "Current Lv"))
        self.currentExpLabel_VJ.setText(_translate("Dialog", "Current Exp"))
        self.expRatio_VJ.setText(_translate("Dialog", "0 / 0 (0%)"))
        self.result_VJ.setTitle(_translate("Dialog", "Result"))
        self.requireMesoLabel_VJ.setText(_translate("Dialog", "Required Cost"))
        self.finishDateLabel_VJ.setText(_translate("Dialog", "Date of Completion"))
        self.remainDateLabel_VJ.setText(_translate("Dialog", "Remaining Days"))
        self.requireMeso_VJ.setText(_translate("Dialog", "0 meso"))
        self.remainDate_VJ.setText(_translate("Dialog", "0 days left"))
        self.finishDate_VJ.setText(_translate("Dialog", str(today)))
        self.questLabel_VJ.setText(_translate("Dialog", "Daily Quest"))
        self.spectrumLabel.setText(_translate("Dialog", "Erda Spectrum"))
        self.reverseCityLabel.setText(_translate("Dialog", "Reverse City"))
        
        self.chuchuIsland.setTitle(_translate("Dialog", "Chu Chu Island"))
        self.currentLevelLabel_CCI.setText(_translate("Dialog", "Current Lv"))
        self.currentExpLabel_CCI.setText(_translate("Dialog", "Current Exp"))
        self.expRatio_CCI.setText(_translate("Dialog", "0 / 0 (0%)"))
        self.result_CCI.setTitle(_translate("Dialog", "Result"))
        self.requireMesoLabel_CCI.setText(_translate("Dialog", "Required Cost"))
        self.finishDateLabel_CCI.setText(_translate("Dialog", "Date of Completion"))
        self.remainDateLabel_CCI.setText(_translate("Dialog", "Remaining Days"))
        self.requireMeso_CCI.setText(_translate("Dialog", "0 meso"))
        self.remainDate_CCI.setText(_translate("Dialog", "0 days left"))
        self.finishDate_CCI.setText(_translate("Dialog", str(today)))
        self.questLabel_CCI.setText(_translate("Dialog", "Daily Quest"))
        self.hungryMutoLabel.setText(_translate("Dialog", "Hungry Muto"))
        self.hungryMuto.setCurrentText(_translate("Dialog", "Easy"))
        self.hungryMuto.setItemText(0, _translate("Dialog", "Easy"))
        self.hungryMuto.setItemText(1, _translate("Dialog", "Normal"))
        self.hungryMuto.setItemText(2, _translate("Dialog", "Hard"))
        self.yumyumIslandLabel.setText(_translate("Dialog", "Yum Yum Island"))
        
        self.lachelein.setTitle(_translate("Dialog", "Lachelein"))
        self.currentLevelLabel_LC.setText(_translate("Dialog", "Current Lv"))
        self.currentExpLabel_LC.setText(_translate("Dialog", "Current Exp"))
        self.expRatio_LC.setText(_translate("Dialog", "0 / 0 (0%)"))
        self.result_LC.setTitle(_translate("Dialog", "Result"))
        self.requireMesoLabel_LC.setText(_translate("Dialog", "Required Cost"))
        self.finishDateLabel_LC.setText(_translate("Dialog", "Date of Completion"))
        self.remainDateLabel_LC.setText(_translate("Dialog", "Remaining Days"))
        self.requireMeso_LC.setText(_translate("Dialog", "0 meso"))
        self.remainDate_LC.setText(_translate("Dialog", "0 days left"))
        self.finishDate_LC.setText(_translate("Dialog", str(today)))
        self.questLabel_LC.setText(_translate("Dialog", "Daily Quest"))
        self.dreamBreakerLabel.setText(_translate("Dialog", "Dream Breaker"))
        
        self.arcana.setTitle(_translate("Dialog", "Arcana"))
        self.currentLevelLabel_AR.setText(_translate("Dialog", "Current Lv"))
        self.currentExpLabel_AR.setText(_translate("Dialog", "Current Exp"))
        self.expRatio_AR.setText(_translate("Dialog", "0 / 0 (0%)"))
        self.result_AR.setTitle(_translate("Dialog", "Result"))
        self.requireMesoLabel_AR.setText(_translate("Dialog", "Required Cost"))
        self.finishDateLabel_AR.setText(_translate("Dialog", "Date of Completion"))
        self.remainDateLabel_AR.setText(_translate("Dialog", "Remaining Days"))
        self.requireMeso_AR.setText(_translate("Dialog", "0 meso"))
        self.remainDate_AR.setText(_translate("Dialog", "0 days left"))
        self.finishDate_AR.setText(_translate("Dialog", str(today)))
        self.questLabel_AR.setText(_translate("Dialog", "Daily Quest"))
        self.spiritSaviorLabel.setText(_translate("Dialog", "Spirit Savior"))
        
        self.morass.setTitle(_translate("Dialog", "Morass"))
        self.currentLevelLabel_MR.setText(_translate("Dialog", "Current Lv"))
        self.currentExpLabel_MR.setText(_translate("Dialog", "Current Exp"))
        self.expRatio_MR.setText(_translate("Dialog", "0 / 0 (0%)"))
        self.result_MR.setTitle(_translate("Dialog", "Result"))
        self.requireMesoLabel_MR.setText(_translate("Dialog", "Required Cost"))
        self.finishDateLabel_MR.setText(_translate("Dialog", "Date of Completion"))
        self.remainDateLabel_MR.setText(_translate("Dialog", "Remaining Days"))
        self.requireMeso_MR.setText(_translate("Dialog", "0 meso"))
        self.remainDate_MR.setText(_translate("Dialog", "0 days left"))
        self.finishDate_MR.setText(_translate("Dialog", str(today)))
        self.questLabel_MR.setText(_translate("Dialog", "Daily Quest"))
        
        self.esfera.setTitle(_translate("Dialog", "Esfera"))
        self.currentLevelLabel_ES.setText(_translate("Dialog", "Current Lv"))
        self.currentExpLabel_ES.setText(_translate("Dialog", "Current Exp"))
        self.expRatio_ES.setText(_translate("Dialog", "0 / 0 (0%)"))
        self.result_ES.setTitle(_translate("Dialog", "Result"))
        self.requireMesoLabel_ES.setText(_translate("Dialog", "Required Cost"))
        self.finishDateLabel_ES.setText(_translate("Dialog", "Date of Completion"))
        self.remainDateLabel_ES.setText(_translate("Dialog", "Remaining Days"))
        self.requireMeso_ES.setText(_translate("Dialog", "0 meso"))
        self.remainDate_ES.setText(_translate("Dialog", "0 days left"))
        self.finishDate_ES.setText(_translate("Dialog", str(today)))
        self.questLabel_ES.setText(_translate("Dialog", "Daily Quest"))

        self.cernium.setTitle(_translate("Dialog", "Cernium"))
        self.currentLevelLabel_CR.setText(_translate("Dialog", "Current Lv"))
        self.currentExpLabel_CR.setText(_translate("Dialog", "Current Exp"))
        self.expRatio_CR.setText(_translate("Dialog", "0 / 0 (0%)"))
        self.result_CR.setTitle(_translate("Dialog", "Result"))
        self.requireMesoLabel_CR.setText(_translate("Dialog", "Required Cost"))
        self.finishDateLabel_CR.setText(_translate("Dialog", "Date of Completion"))
        self.remainDateLabel_CR.setText(_translate("Dialog", "Remaining Days"))
        self.requireMeso_CR.setText(_translate("Dialog", "0 meso"))
        self.remainDate_CR.setText(_translate("Dialog", "0 days left"))
        self.finishDate_CR.setText(_translate("Dialog", str(today)))
        self.questLabelCR.setText(_translate("Dialog", "Daily Quest"))
        
        self.hotelArcs.setTitle(_translate("Dialog", "Hotel Arcs"))
        self.currentLevelLabel_HA.setText(_translate("Dialog", "Current Lv"))
        self.currentExpLabel_HA.setText(_translate("Dialog", "Current Exp"))
        self.expRatio_HA.setText(_translate("Dialog", "0 / 0 (0%)"))
        self.result_HA.setTitle(_translate("Dialog", "Result"))
        self.requireMesoLabel_HA.setText(_translate("Dialog", "Required Cost"))
        self.finishDateLabel_HA.setText(_translate("Dialog", "Date of Completion"))
        self.remainDateLabel_HA.setText(_translate("Dialog", "Remaining Days"))
        self.requireMeso_HA.setText(_translate("Dialog", "0 meso"))
        self.remainDate_HA.setText(_translate("Dialog", "0 days left"))
        self.finishDate_HA.setText(_translate("Dialog", str(today)))
        self.questLabel_HA.setText(_translate("Dialog", "Daily Quest"))
import ArcaneSymbol_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
